### ISSUE TITLE
sql parser uncaught error

### ISSUE THREAD

**Issue by snowwhite686** [thecodingmachine/mouf-html.widgets.evolugrid#33]
Hi,

When i try to create a evolugrid, i get the following error, please check the screenshots. As per the DAO, jobseekers table is already created.
![capture_createevolugrid](https://cloud.githubusercontent.com/assets/3541070/21001511/b5dbd9da-bd46-11e6-8119-89008f18d3e2.JPG)
![capture_evolerror](https://cloud.githubusercontent.com/assets/3541070/21001507/b4cfecde-bd46-11e6-98c4-9f2e46d8ffba.JPG)

PLease help i think the sql parser package is already with the auto installation? or is there any explicit way to include them? please advise.

Thanks
Neetha

**Comment by xhuberty** [comment]
Hi,

Thanks for creating the issue. The namespace of SQLParser class changed.
We have corrected this issue in the 5.2.0 release, just do a composer update.

Best regards.

**Comment by snowwhite686** [comment]
thank you , its working.
