### ISSUE TITLE
url link - grid error

### ISSUE THREAD

**Issue by snowwhite686** [thecodingmachine/mouf-html.widgets.evolugrid#35]
Hi,

I created a grid instance and tried accessing the below url and i get the following error.
![capture_controller](https://cloud.githubusercontent.com/assets/3541070/21010637/2dfd6a56-bd73-11e6-8aee-98abd5106394.JPG)
![capture_evol4](https://cloud.githubusercontent.com/assets/3541070/21010686/83ed133a-bd73-11e6-935a-2eec780ffb5b.JPG)
![capture_evol3](https://cloud.githubusercontent.com/assets/3541070/21010687/83f0c96c-bd73-11e6-9203-f26f08c79131.JPG)
![capture_evol2](https://cloud.githubusercontent.com/assets/3541070/21010688/8436f77a-bd73-11e6-88ff-3f2e869b20d6.JPG)
![capture_evol1](https://cloud.githubusercontent.com/assets/3541070/21010689/843d2ee2-bd73-11e6-964d-dd137e779366.JPG)

http://localhost/gmvc/getting-things-done-basic-edition/getseekerslist

Not sure, am i missing something?

please help.

thanks
neetha

**Comment by xhuberty** [comment]
It seems that the dataset given to the resultSet isn't iterable that's why you get the warning : 
"Invalid argument suplied for foreach"

I have never use this package with SQL query for feeding the resultSet. If no one answer this I will try to have a look at it.
