### ISSUE TITLE
grid instance in controller

### ISSUE THREAD

**Issue by snowwhite686** [thecodingmachine/mouf-html.widgets.evolugrid#36]
Other than the automated grid issue referred before, i tried following up the documentation using php code. //Complete EvoluGrid sample using Splash MVC framework and pure PHP code from (doc/view/mouf/html.widgets.evolugrid/doc/evolugrid_php.md)

But I am getting error like

![capture_geterror1](https://cloud.githubusercontent.com/assets/3541070/21041439/00ab3a1c-be11-11e6-9a22-6e31bc545c3b.JPG)
![capture_geterror2](https://cloud.githubusercontent.com/assets/3541070/21041444/06eba5d8-be11-11e6-9fda-01d2270e92ed.JPG)

please check my controller code

[UserController.txt](https://github.com/thecodingmachine/mouf-html.widgets.evolugrid/files/641506/UserController.txt)
[register-twig.txt](https://github.com/thecodingmachine/mouf-html.widgets.evolugrid/files/641509/register-twig.txt)
![capture_dbpic1](https://cloud.githubusercontent.com/assets/3541070/21041647/62e55dba-be12-11e6-9278-25a5b6fa576d.JPG)

Please help, is there any missing params in @get param in the declaration method comment or call?

Thanks
Neetha

.

**Comment by xhuberty** [comment]
You have to import the @Get annotation. To do so just add this use : 
use Mouf\Mvc\Splash\Annotations\Get;

Here are some other usefull annotation :
use Mouf\Mvc\Splash\Annotations\Post;
use Mouf\Mvc\Splash\Annotations\URL;
use Mouf\Security\Logged;

**Comment by snowwhite686** [comment]
Now its a different error,everything is vague now..please help.

![capture_evolugridd](https://cloud.githubusercontent.com/assets/3541070/21174368/bccd2170-c202-11e6-9e1e-b9fe81bc3c49.JPG)
[Usercontroller_details.txt](https://github.com/thecodingmachine/mouf-html.widgets.evolugrid/files/651092/Usercontroller_details.txt)

**Comment by moufmouf** [comment]
Same thing here. You did not put a `use` statement at the top of the file to import the Evolugrid class.

Something like:

```php
use Mouf\Html\Widgets\EvoluGrid\EvoluGrid;
```

What IDE are you using? You should use an IDE like Eclipse + PDT or Netbeans or PHPStorm. Those IDEs will automatically warn you if you forget a "use" statement and will propose features to autocomplete the list of use statements at the top of your file. They are hugely helpful when coding in PHP.

**Comment by snowwhite686** [comment]
am using Adobe dreamweaver, i added the stmt and now the same error i addressed in another thread..!!
![capture_errorevolu](https://cloud.githubusercontent.com/assets/3541070/21176104/4b84c410-c20b-11e6-948e-265209065f2c.JPG)
[Usercontroller_details2.txt](https://github.com/thecodingmachine/mouf-html.widgets.evolugrid/files/651231/Usercontroller_details2.txt)


As i can see the grid parameter is passed to the view, i really dont know why is it showing the output detected directly error. or is your grid functions doing anything to display the grid directly? May be the tohtml function only?

Please help me further. Also can't i just display any data directly further then? 
thanks
neetha

**Comment by xhuberty** [comment]
You just have to understand the error you get and look at your file line 80 and you will see instantly how to correct the error.

**Comment by snowwhite686** [comment]
no, that's why i said you clearly that it's showing error on line where the
grid variable is passed. i used the documentation code onky for Evolugrid.
The example code itself is showing error, that's why i came to you for
further clarification. if you can check i have attached the controller
files.

yesterday you advised to add the use statements ( even if it's not in the
documentation shown in website) .

But i think it's something about missing codes may be in tohtml function or
the inbuilt library may be?

Thanks
Neetha

**Comment by xhuberty** [comment]
If you look at the correct line you will see that the variable is $evolugrid but the only variable define 5 lines before is $evoluGrid.

You just have to change the lower case "g" of the variable un upper case.

**Comment by snowwhite686** [comment]
i changed the variable, now when i load 
http://localhost/gmvc/getting-things-done-basic-edition/register it is blank . and also when i try to get the response from http://localhost/gmvc/getting-things-done-basic-edition/getlist it says Class 'Test\Controllers\EvoluGridResultSet' not found error.

Please help me  :( as we have not yet started to do the exact requirement yet. If only we get the right way through, then only we can move ahead with this mouf framework, thats why. i hope you can understand my situation. 

[register.txt](https://github.com/thecodingmachine/mouf-html.widgets.evolugrid/files/655320/register.txt)
Please check my view file.
Thanks
Neetha
